import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  metadataBase: new URL('https://infinitynetwork.mx/'),
  icons: {
    icon: './images/infinity/square_logo.svg',
  },
  title: "Infinity Network",
  description: "Generated by create next app",
  robots: 'index, follow',
  openGraph: {
    title: 'Infinity Network',
    description: 'Generated by create next app',
    url: 'https://mi-sitio.com',
    images: ['https://mi-sitio.com/imagen.jpg']
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Infinity Network',
    description: 'Generated by create next app',
    images: 'https://mi-sitio.com/imagen.jpg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
